image: rikorose/gcc-cmake
stages:
  - clean
  - build
  - test
  - docs
  - deploy
before_script:
  - "apt-get update -qq && apt-get install -y -qq libevent-dev"
makeclean:
  stage: clean
  script:
    - "cd examples"
    - "make clean"
makeLibevent:
  stage: build
  script:
    - "cd examples"
    - "make"
makeNoLibevent:
  stage: build
  script:
    - "cd examples"
    - "NO_LIBEVENT=1 make"
cmakeTests:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SSL_NO_VERIFY: "true"
  stage: test
  script:
    - "cd tests"
    - "mkdir build"
    - "cd build"
    - "cmake .."
    - "make"
    - "./runTests"
doxygenDocs:
  before_script: []
  stage: docs
  image: iimuz/doxygen
  when: always
  script:
    - "mkdir -p build/doxygen"
    - "doxygen Doxyfile"
  artifacts:
    paths:
      - "build/doxygen"
pages:
  stage: deploy
  dependencies:
    - doxygenDocs
  before_script: []
  script:
    - "rm -rf public"
    - "mkdir -p public"
    - "cp -r docs/* public"
    - "mkdir -p public/doxygen"
    - "cp -r build/doxygen/html/* public/doxygen"
  artifacts:
    paths:
    - public
  only:
  - master