stages:
  - clean
  - build
before_script:
  - "apt-get update -qq && apt-get install -y -qq libevent-dev make gcc"
makeclean:
  stage: clean
  script:
    - "cd examples"
    - "make clean"
makeLibevent:
  stage: build
  script:
    - "cd examples"
    - "make"
makeNoLibevent:
  stage: build
  script:
    - "cd examples"
    - "NO_LIBEVENT=1 make"